```{r}
library(ggplot2)
library(psych) # Contains the winsor function and other helpful statistical tools
library(tidyverse) # Remember from last homework that dplyr is included in tidyverse
library(gridExtra)
library(corrplot)
library(patchwork)
library(utils)
library(factoextra)
library(tidyverse)
library(MASS)
library(ROCR)
library(caret)
library(gmodels)
library(caTools)
library(class)

set.seed(580)
library(RColorBrewer) #easier to see correlation matrix
```


```{r}
EEGdata <- readRDS("/Users/christian/Documents/BME580/EEGnew.rds")


#corrdf <- cor(subset(EEGdata, select= -c(diagnosis)))
#corrplot(corrdf, type = 'upper', method='number',tl.col="black", tl.srt=45, title='Correlation of EEG Data', mar=c(0,0,1,0), col=brewer.pal(n=10,name="RdBu"))
```

```{r}
scaleData = EEGdata
scaleData[2:281] = scale(EEGdata[2:281])
```

```{r}
pr.out=prcomp(scaleData[2:281], scale=TRUE)
summary(pr.out)
```

```{r}
get_eig(pr.out)
pr.out$rotation
```

```{r}
fviz_eig(pr.out, addlabels = TRUE)
fviz_eig(pr.out, addlabels = TRUE)
fviz_pca_biplot(pr.out,col.ind='coord', #color of dots depends on size of loading
             repel = T) #makes sure names dont overlap)
```

KNN

```{r}
dataknn = sample.split(scaleData$diagnosis, 70/100) # only 84 observations so small
train = subset(scaleData, dataknn == TRUE)
test = subset(scaleData, dataknn == FALSE)
mod_knn = knn(train,test,cl=train$diagnosis,k=round(sqrt(nrow(train))))

confusionTab = table(Predicted = mod_knn, Actual = test$diagnosis)
confusionTab
```

```{r}
prec_mod = (confusionTab[2,2])/(confusionTab[2,2]+confusionTab[2,1])
print(paste("Precision:",prec_mod))
acc_mod = (confusionTab[1,1]+confusionTab[2,2])/length(test$diagnosis)
print(paste("Accuracy:",acc_mod))
err_mod = 1-acc_mod
print(paste("Error rate:", err_mod))
sens_mod = (confusionTab[2,2])/(confusionTab[2,2]+confusionTab[1,2])
print(paste("Sensitivity", sens_mod))
```

```{r}
folds = createFolds(scaleData$diagnosis,k=4)
folds

fold1_knn = knn(scaleData[c(folds$Fold2,folds$Fold3,folds$Fold4),],scaleData[folds$Fold1,],cl=scaleData$diagnosis[c(folds$Fold2,folds$Fold3,folds$Fold4)],k=round(sqrt(length(folds$Fold1))))
cT1 = table(Predicted = fold1_knn, Actual = scaleData$diagnosis[folds$Fold1])

fold2_knn = knn(scaleData[c(folds$Fold1,folds$Fold3,folds$Fold4),],scaleData[folds$Fold2,],cl=scaleData$diagnosis[c(folds$Fold1,folds$Fold3,folds$Fold4)],k=round(sqrt(length(folds$Fold2))))
cT2 = table(Predicted = fold2_knn, Actual = scaleData$diagnosis[folds$Fold2])
fold3_knn = knn(scaleData[c(folds$Fold2,folds$Fold1,folds$Fold4),],scaleData[folds$Fold3,],cl=scaleData$diagnosis[c(folds$Fold2,folds$Fold1,folds$Fold4)],k=round(sqrt(length(folds$Fold3))))
cT3 = table(Predicted = fold3_knn, Actual = scaleData$diagnosis[folds$Fold3])
fold4_knn = knn(scaleData[c(folds$Fold2,folds$Fold3,folds$Fold1),],scaleData[folds$Fold4,],cl=scaleData$diagnosis[c(folds$Fold2,folds$Fold3,folds$Fold1)],k=round(sqrt(length(folds$Fold4))))
cT4 = table(Predicted = fold4_knn, Actual = scaleData$diagnosis[folds$Fold4])
cT1
cT2
cT3
cT4

acc1 = (cT1[1,1]+cT1[2,2])/length(folds$Fold1)
acc2 = (cT2[1,1]+cT2[2,2])/length(folds$Fold2)
acc3 = (cT3[1,1]+cT3[2,2])/length(folds$Fold3)
acc4 = (cT4[1,1]+cT4[2,2])/length(folds$Fold4)
avg_acc = mean(acc1,acc2,acc3,acc4)
avg_acc
```

